### ISSUE TITLE
Add new test cases for Trade into in.txt

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-cli#105]

**Comment by 1fifoto** [comment]
I believe that I have confirmed my earlier concerns about Trade arbitrary.  I have opened PCyl-CLI issue #105 (Add new test cases for Trade into in.txt).  I created a mini trade1.txt and executed "npm run coverage1" to produce actual_out_trade1.txt.  Those two files plus the modified package.json file have been pushed to branch 105.  You can get access to them there.  I see trivial differences with the PL/I result but significant differences with the web result.  Separately, I discovered one significant and one trivial issue with Trade in CLI.  The more significant issue could carry over into web.  I will leave it up to you as to when to work on this specific issue.  In the mean time, I have plenty to do in creating more test cases for Trade in in.txt.

**Comment by grumpyinca** [comment]
Refer to PCyl-Web issue #127.  [title](link)

**Comment by grumpyinca** [comment]
Closing without merging into master.

The naming conventions for files in the test directory were changed in branch 105.  Merging these files would likely create confusion.


A new issue will be opened to carry further test case development for Trade.
