### ISSUE TITLE
Future version food for thought ... rename the START command to "Edit" or "Open"

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-cli#9]
In order to better communicate that the program can be thought of as an "editor" for design files, it might be desirable to rename the START command to "Edit" or "Open".

**Comment by 1fifoto** [comment]
I thought you also said to change 'checkpoint' or 'ckpt' to save.

**Comment by grumpyinca** [comment]
This issue is being handled in the PCyl-web menu definitions.  Closing here.
